<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitXMLReporter -->
<testsuite hostname="VicdeMac.local" ignored="0" name="applyContinueTest" tests="1" failures="1" timestamp="10 Sep 2020 02:38:18 GMT" time="21.885" errors="0">
  <testcase name="testApplyContinue" time="14.203" classname="test.ApplyContinueTest">
    <failure type="java.lang.AssertionError" message="检查点不通过 expected [true] but found [false]">
      <![CDATA[java.lang.AssertionError: 检查点不通过 expected [true] but found [false]
	at test.ApplyContinueTest.testApplyContinue(ApplyContinueTest.java:36)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
... Removed 19 stack frames]]>
    </failure>
  </testcase> <!-- testApplyContinue -->
</testsuite> <!-- applyContinueTest -->
